### ISSUE TITLE
ACK-less mode

### ISSUE THREAD

**Issue by IvanSanchez** [JadKHaddad/tm1637#5]
One of my use cases for using TM1637 displays is using a FTDI FT232H - a small USB peripheral to drive (`embedded-hal`-compatible) GPIOs from a laptop, by means of the [`ftdi_embedded_hal` crate](https://docs.rs/ftdi-embedded-hal/latest/ftdi_embedded_hal/).

![IMG_20240829_134143](https://github.com/user-attachments/assets/a57fe499-bd3d-4cc7-a0f7-b01500a8f317)

The issue is that the FTDI GPIO pins can be configured in ***either*** input or output mode. In other words: it's impossible to configure its pins in input+output mode.

This is a problem because the `DIO` pin must be an input-output pin, at...

https://github.com/JadKHaddad/tm1637/blob/e785ba96e3d99eb96593c22ea47f45a8a7ae2c48/tm1637/src/device.rs#L103

...but if I change that into...

```rust
            DIO: /*InputPin<Error = ERR> +*/ OutputPin<Error = ERR>,
```

...then everything works just fine with my FTDI output-only pins.

This is currently not a problem since acknowledgments are not implemented (#2). So I suggest this crate should have two working modes: one with acknowledgments (where `DIO` is required to implement both the `InputPin` and `OutputPin` traits), and one without (where `DIO` is required to implement *only* the `OutputPin` trait).

**Comment by JadKHaddad** [comment]
Can be removed for now. I will take care of it
